name: gitkraken
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Unleash your repo.
description: |
  The best Git client should integrate with your Git hosting service. That’s why GitKraken connects to popular services like GitHub, Bitbucket and GitLab to make working with your remote repositories easier.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64]

parts:
  gitkraken:
    plugin: dump
    source: https://release.gitkraken.com/linux/gitkraken-amd64.deb
    source-type: deb
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://www.gitkraken.com/download -q -S -O - 2>&1 | grep Latest | awk '{print $4}' | sed 's|</strong></p>||')
      echo $ver > $SNAPCRAFT_STAGE/version
      sed -i 's|Icon=app|Icon=/usr/share/pixmaps/app\.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/gitkraken.desktop
    after:
      - desktop-gtk2
    build-packages:
      - wget
    stage-packages:
      - gconf2
      - gconf-service
      - libnotify4
      - libxtst6
      - libxkbfile1
      - libxss1
      - libnss3
      - librtmp1
      - libcurl3
      - python
      - gvfs-bin
      - libgnome-keyring0
      - gir1.2-gnomekeyring-1.0
      - libcanberra-gtk-module
      - libatk-adaptor
      - libgail-common
      - overlay-scrollbar-gtk2
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian

  desktop-gtk2:
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
      - -bindtextdomain.so

apps:
  gitkraken:
    command: bin/desktop-launch $SNAP/usr/share/gitkraken/gitkraken
    desktop: usr/share/applications/gitkraken.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - gsettings
      - home
      - network
      - opengl
      - unity7
      - wayland
      - x11
      - removable-media
      - ssh-keys
