name: gitkraken
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Unleash your repo.
description: |
  The best Git client should integrate with your Git hosting service. That’s why GitKraken connects to popular services like GitHub, Bitbucket and GitLab to make working with your remote repositories easier.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64]

parts:
  gitkraken:
    plugin: nil
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://www.gitkraken.com/download -q -S -O - 2>&1 | grep Latest | awk '{print $4}' | sed 's|</strong></p>||')
      echo $ver > $SNAPCRAFT_STAGE/version
      wget https://release.gitkraken.com/linux/gitkraken-amd64.deb && dpkg-deb -xv gitkraken-amd64.deb .
      cp -R -p usr $SNAPCRAFT_PART_INSTALL/
      sed -i 's|Icon=app|Icon=/usr/share/pixmaps/app\.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/gitkraken.desktop
    after:
      - desktop-gtk2
    build-packages:
      - wget
    stage-packages:
      - gconf2
      - gconf-service
      - libasound2
      - libnotify4
      - libxtst6
      - libxkbfile1
      - libxss1
      - libnss3
      - librtmp1
      - libcurl3
      - libgck-1-0
      - libgcr-base-3-1
      - libgtk2.0-0
      - python
      - gvfs-bin
      - gvfs-libs
      - gvfs-common
      - gvfs-daemons
      - libgcrypt20
      - libgnome-keyring0
      - gir1.2-gnomekeyring-1.0
      - git
      - git-lfs
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
      - -usr/bin/gitkraken

  desktop-gtk2:
    after:
      - git-lfs
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian

  git-lfs:
    plugin: nil
    override-build: |
      curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
    build-packages:
      - curl
      - gnupg
      - software-properties-common
      - apt-transport-https

apps:
  gitkraken:
    command: bin/desktop-launch $SNAP/usr/share/gitkraken/gitkraken
    desktop: usr/share/applications/gitkraken.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to
    # ensure libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - gsettings
      - home
      - network
      - opengl
      - unity7
      - wayland
      - x11
      - removable-media
      - ssh-keys
